### ISSUE TITLE
host page - 이벤트 body - 공통

### ISSUE THREAD

**Issue by hkwon** [connect-foundation/2019-21#19]
기능번호: 5
우선순위: 상
난이도: 하

# host page - 이벤트 body - 공통

-   [x] (공통) 각 컬럼에는 필터버튼(낮은 우선순위)
-   [x] 각 컬럼에는 정렬버튼(낮은 우선순위)

**Comment by nuguya** [comment]
1. 컬럼별로 상태관리 및 보여지는 부분 변경
