### ISSUE TITLE
Light House 지표 개선 

### ISSUE THREAD

**Issue by teihong93** [connect-foundation/2019-21#249]
- light house 퍼포먼스 올리기
- 2019/11/29 기준 현재 점수: `2`
- [x] 20 이상
- [x] 30 이상
- [ ] 40 이상
- [ ] 50 이상

<img width="1175" alt="lh" src="https://user-images.githubusercontent.com/52785648/69855804-a2f95180-12cf-11ea-889c-13c61308998c.png">

**Comment by hkwon** [comment]
Sli.do light house 결과도 알아보고 시작합시다.

2019년 11월 29일 (금) 오후 5:44, Teihong93 <notifications@github.com>님이 작성:

**Comment by teihong93** [comment]
<img width="1567" alt="lh_origin" src="https://user-images.githubusercontent.com/52785648/69915653-e5b85680-1494-11ea-911e-758cde27ae04.png">
재밌네요.... sli.do 는 20점입니다!
이겨볼만 하네요 sli.do

**Comment by teihong93** [comment]
- 2019/12/13 기준 현재 점수: `35`

<img width="1274" alt="lh_3" src="https://user-images.githubusercontent.com/52785648/70769748-14e09900-1dae-11ea-8aff-5d784fd1e755.png">

**Comment by teihong93** [comment]
35로 종료합니다.
