### ISSUE TITLE
[BUG] 이벤트url로 들어가면 에러페이지가 뜹니다.

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-21#347]
이벤트 url을 복사하여 들어갔는데 에러페이지가 나와요!
http://vaagle.com/Y2xkeQ==

<img width="504" alt="스크린샷 2019-12-06 오후 3 01 58" src="https://user-images.githubusercontent.com/29801123/70299860-654d7900-1839-11ea-9986-a52afeb976b7.png">

**Comment by demetoir** [comment]
해결됨 

버그 이유: 도메인주소에 www가 누락됨
