### ISSUE TITLE
react app의 favicon 및 제목 설정하기

### ISSUE THREAD

**Issue by demetoir** [connect-foundation/2019-21#355]
- [x] host app favicon 설정하기
- [x] guest app favicon 설정하기
- [x] main app favicon 설정하기
- [x] host app html title 설정
- [x] guest app html title 설정
- [x] main app html title 설정

**Comment by teihong93** [comment]
![va22](https://user-images.githubusercontent.com/52785648/70370218-af9d2b80-1907-11ea-978c-274532aac4f9.png)
- 임시 파비콘

**Comment by teihong93** [comment]
-.ico 파일
[cc1303538beef602b12909d3145bc015.ico.zip](https://github.com/connect-foundation/2019-21/files/3934823/cc1303538beef602b12909d3145bc015.ico.zip)
