### ISSUE TITLE
socket.io 서버에서 이벤트별 글로벌 데이터를 저장할 redis가 필요

### ISSUE THREAD

**Issue by demetoir** [connect-foundation/2019-21#356]
socket.io에서 처리할 이벤트별 글로벌데이터를 싱글톤 객체로 가지고 있음
host app을 안키고 guest app으로 이벤트에 들어갔을때 싱글톤 객체에 이벤트의 글로벌 데이터가 없어 moderationOption is undefine 에러 를 발생함
docker로 redis 서버를 만든후 글로벌 데이터를 저장해놓아야함

**Comment by teihong93** [comment]
서버를 껐다 켰을 떄, 한번도 host-app 으로 들어가지 않고, 존재하는 enevtCode로 guset 가 접근하면 문제가 생기는군요...
굳이 redis까지 구축할 필요 없이, socket-io 서버가 켜지면 sequelize로 DB에 존재하는 모든 eventCode에 대한 Option 정보를 불러와 socket-io 싱글톤에 넣어주는 과정만 추가해도 되지 않을까요?  redis를 하나 더 운영하는것도 오버헤드가 있을 것 같아서요!

**Comment by demetoir** [comment]
이미 만들어서 개발모드에서 바로 할 수 있도록 docker 세팅까지 해놨습니다. .......

**Comment by teihong93** [comment]
엇 그렇다면 redis로 갑시다!! 고생하였습니다!
