### ISSUE TITLE
[BUG] 버튼 클릭시 프로필 색이 계속 바뀝니다

### ISSUE THREAD

**Issue by GirlFriend-Yerin** [connect-foundation/2019-21#432]
권한 : 이벤트 주최자

이벤트 주최시 프로필(?) 색이 계속 바뀝니다.
상단의 오른쪽에 있는 라디오 버튼 클릭시 프로필 색이 계속 바뀝니다.

**Comment by demetoir** [comment]
#439 이슈와 동일한 버그
