### ISSUE TITLE
[BUG] 질문이 올라가지 않습니다.

### ISSUE THREAD

**Issue by load0ne** [connect-foundation/2019-21#434]
## 재연

질문을 추가로 계속 올려봤는데 생성이 되지 않고 있어요 😢

<img width="377" alt="스크린샷 2019-12-13 오후 2 55 51" src="https://user-images.githubusercontent.com/47515936/70772707-afde7080-1db8-11ea-8ab8-c3956115e706.png">

**Comment by teihong93** [comment]
해결되어 이슈를 종료합니다
