### ISSUE TITLE
배포 자동화 

### ISSUE THREAD

**Issue by teihong93** [connect-foundation/2019-21#492]
#### 배포 자동화 프로세스 구축
- `master` 브랜치에 push 되면 자동으로 빌드하여 배포되도록 수정해야 함

**Comment by demetoir** [comment]
맴버쉽 종료 이후 리포 날리면서 리포 권한도 날라갔습니다. 제가 2/17(월)에 부캠 스태프분들에게 연락해서 권한가져온뒤, 팀원 모두에게 권한 부여하겠습니다.

**Comment by demetoir** [comment]
부캠에서 더이상 손못대도록 일부로 admin 권한은 주지않았다고 합니다. fork 한 리포에만 업데이트 하라고 하네요
