### ISSUE TITLE
DB - 스키마 설계

### ISSUE THREAD

**Issue by demetoir** [connect-foundation/2019-21#54]
1. [x] 구현에 필요한 테이블 목록 추출
2. [x] 각 테이블이 갖는 Attribute 추출
3. [x] 테이블간 관계 설정
4. [x] 설계 산출물 추가

**Comment by nuguya** [comment]
1. [ ] 기능 구현에 필요한 테이블 목록 추출
2. [ ] 각 테이블이 갖는 Attribute 추출
3. [ ] 테이블간 관계 설정

**Comment by nuguya** [comment]
![erdv5](https://user-images.githubusercontent.com/35131398/68749310-5a8c3380-0641-11ea-82e4-4b61febd90ef.png)

**Comment by nuguya** [comment]
태의님과 권혁님과 근영님의 합작품 :)
