### ISSUE TITLE
테스트 코드 실행하는 script 에러

### ISSUE THREAD

**Issue by nuguya** [connect-foundation/2019-21#91]
test 스크립트는 실행가능 한데 아래 스크립트는 실행이 안되는 걸 보니
"test:DB": "./node_modules/.bin/mocha $(find ./spec -name '*.db.spec.js') --recursive --watch" 이 명령어가 mac에서만 사용 가능한 것 같습니다. 윈도우에서는 해당 스크립트가 실행되지 않네요

**Comment by teihong93** [comment]
앗 이슈 해결해서 다시 PR 드리겠습니다!
